services:
  api:
    build: .
    container_name: apime-api
    command: sh -c "./migrate -with-seeds && ./api"
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - apime_data:/app/data
    restart: unless-stopped

volumes:
  apime_data: