services:
  api:
    build: .
    container_name: apime-api
    command: sh -c "./migrate -with-seeds && ./api"
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - apime_data:/app/data
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: apime-redis
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

volumes:
  apime_data:
  redis: